# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-16 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustLoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('oa_session_key', models.CharField(max_length=64)),
                ('session_id', models.CharField(max_length=64)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
