# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-16 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custloginrecord',
            name='session_id',
        ),
    ]
