# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_remove_custloginrecord_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('website', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('facebook', models.CharField(max_length=64)),
                ('youtube', models.CharField(max_length=64)),
                ('twitter', models.CharField(max_length=64)),
                ('search_word', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32)),
                ('place_id', models.CharField(max_length=128)),
            ],
        ),
    ]
