# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='country',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='facebook',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='twitter',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='website',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='youtube',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
