# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-17 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_searchresult_td_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
