# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spider', '0008_auto_20200617_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='place_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
