# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0012_auto_20200617_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='facebook',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='twitter',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='website',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='youtube',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
