# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-18 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spider', '0014_auto_20200617_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
