# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-06-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spider', '0022_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDayCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'RequestDayCount',
            },
        ),
        migrations.CreateModel(
            name='RequestDetailDayCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'RequestDetailDayCount',
            },
        ),
    ]
