# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-06-07 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0023_requestdaycount_requestdetaildaycount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestDayCount',
        ),
        migrations.DeleteModel(
            name='RequestDetailDayCount',
        ),
    ]
